name: Play Store Internal

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build:
    name: Play Store
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: version
        run: |
          run_number=${{ github.run_number }}
          tag=${GITHUB_SHA::7}
          release=$(printf ci%06d $run_number)
          echo "run_number=$run_number" >> "$GITHUB_OUTPUT"
          echo "tag=$tag" >> "$GITHUB_OUTPUT"
          echo "buildname=$tag" >> "$GITHUB_OUTPUT"
          echo "buildnumber=$run_number" >> "$GITHUB_OUTPUT"
          echo "release=$release" >> "$GITHUB_OUTPUT"
      - name: Update gradle key.properties
        run: |
          echo $'\n' >> android/key.properties
          echo $'keyPassword=${{ secrets.ANDROID_KEYSTORE_PASS }}\n' >> android/key.properties
          echo $'storePassword=${{ secrets.ANDROID_KEYSTORE_PASS }}\n' >> android/key.properties
      - name: Retrieve the signing key and decode it to a file
        env:
          ANDROID_SIGNING_KEY: ${{ secrets.ANDROID_SIGNING_KEY }}
        run: |
          echo $ANDROID_SIGNING_KEY | base64 --decode > android/app/fordem.jks
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v2.3.0
        with:
          channel: "master"
      - run: flutter pub get
      - run: flutter test
      - name: Build Android Bundle
        run: flutter build appbundle --dart-define VERSION=${{ steps.version.outputs.tag }} --build-name ${{ steps.version.outputs.buildname }} --build-number ${{ steps.version.outputs.buildnumber }}
      - name: Release app to internal track
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAYSTORE_ACCOUNT_KEY }}
          packageName: org.fordem.app
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          track: internal
